#!/usr/bin/env Rscript
# sync_db.R
# Compile entries from reproducr-db into R/breaking_changes_db.R
#
# Usage (from reproducr package root):
#   Rscript data-raw/sync_db.R
#
# Requires reproducr-db to be cloned alongside the reproducr repo:
#   ../reproducr-db/entries/
#
# Or set the REPRODUCR_DB_PATH environment variable:
#   REPRODUCR_DB_PATH=/path/to/reproducr-db Rscript data-raw/sync_db.R

library(jsonlite)

db_path <- Sys.getenv(
  "REPRODUCR_DB_PATH",
  unset = file.path(dirname(getwd()), "reproducr-db")
)

entries_path <- file.path(db_path, "entries")

if (!dir.exists(entries_path)) {
  stop(
    "reproducr-db not found at: ", entries_path, "\n",
    "Clone it with:\n",
    "  git clone https://github.com/repro-stats/reproducr-db ../reproducr-db\n",
    "Or set REPRODUCR_DB_PATH to the correct path."
  )
}

# ---- Read all JSON entries --------------------------------------------------

json_files <- list.files(entries_path,
  pattern = "\\.json$",
  recursive = TRUE, full.names = TRUE
)

cat(sprintf("Found %d entry files in %s\n", length(json_files), entries_path))

entries <- lapply(json_files, function(f) {
  tryCatch(
    jsonlite::fromJSON(f, simplifyVector = TRUE),
    error = function(e) {
      warning("Failed to parse: ", f, " -- ", conditionMessage(e))
      NULL
    }
  )
})
entries <- Filter(Negate(is.null), entries)
cat(sprintf("Successfully parsed %d entries\n", length(entries)))

# ---- Sanitise all string fields to ASCII ------------------------------------
# Replaces non-ASCII characters (e.g. em dashes, curly quotes, degree symbols)
# with ASCII equivalents. This prevents R CMD check WARNING on Windows/CRAN.

.to_ascii <- function(s) {
  if (is.null(s) || !is.character(s)) {
    return(s)
  }
  # Common Unicode -> ASCII replacements
  s <- gsub("\u2014", "--", s) # em dash
  s <- gsub("\u2013", "-", s) # en dash
  s <- gsub("\u00b0", " deg", s) # degree symbol
  s <- gsub("\u2019", "'", s) # right single quote
  s <- gsub("\u2018", "'", s) # left single quote
  s <- gsub("\u201c", '"', s) # left double quote
  s <- gsub("\u201d", '"', s) # right double quote
  s <- gsub("\u00e9", "e", s) # e acute
  s <- gsub("\u00e8", "e", s) # e grave
  # Final fallback: replace any remaining non-ASCII with ?
  iconv(s, from = "UTF-8", to = "ASCII", sub = "?")
}

entries <- lapply(entries, function(e) {
  e$description <- .to_ascii(e$description)
  e$reference <- .to_ascii(e$reference)
  e$fn <- .to_ascii(e$fn)
  if (!is.null(e$closed_reason)) {
    e$closed_reason <- .to_ascii(e$closed_reason)
  }
  e
})

# ---- Group by pkg::fn -------------------------------------------------------

keys <- vapply(entries, function(e) paste0(e$pkg, "::", e$fn), character(1L))
grouped <- split(entries, keys)
grouped <- grouped[order(names(grouped))]
pkgs <- sort(unique(vapply(entries, `[[`, character(1L), "pkg")))

# ---- Helper: escape a string for R source ----------------------------------

r_string <- function(s) {
  s <- gsub('"', '\\\\"', s)
  parts <- strwrap(s, width = 60)
  if (length(parts) == 1L) {
    sprintf('"%s"', parts)
  } else {
    inner <- paste(sprintf('"%s"', parts), collapse = ",\n        ")
    sprintf("paste0(\n        %s\n      )", inner)
  }
}

# ---- Helper: emit one entry list() -----------------------------------------

emit_entry <- function(e, comma) {
  is_closed <- isTRUE(e$closed)
  lines <- c(
    "    list(",
    sprintf('      from_version = "%s",', e$from_version),
    sprintf('      to_version   = "%s",', e$to_version),
    sprintf('      risk         = "%s",', e$risk),
    sprintf("      description  = %s,", r_string(e$description))
  )
  if (is_closed) {
    lines <- c(
      lines,
      sprintf('      reference    = "%s",', e$reference),
      "      closed       = TRUE"
    )
  } else {
    lines <- c(
      lines,
      sprintf('      reference = "%s"', e$reference)
    )
  }
  lines <- c(lines, sprintf("    )%s", comma))
  lines
}

# ---- Build output lines -----------------------------------------------------

header <- c(
  "# Breaking changes database for reproducr",
  "#",
  "# AUTO-GENERATED by data-raw/sync_db.R -- do not edit by hand.",
  "# Source of truth: https://github.com/repro-stats/reproducr-db",
  "#",
  sprintf(
    "# Generated: %s", format(Sys.time(), "%Y-%m-%d %H:%M UTC", tz = "UTC")
  ),
  sprintf(
    "# Entries:   %d across %d pkg::fn keys",
    length(entries), length(grouped)
  ),
  "#",
  "# Schema per entry:",
  "#   from_version : last safe version (exclusive lower bound)",
  "#   to_version   : last risky version (inclusive upper bound)",
  "#   risk         : 'high' | 'medium' | 'low'",
  "#   description  : plain-English explanation",
  "#   reference    : URL to official changelog",
  "#   closed       : TRUE if window is intentionally closed",
  "#                  (skipped by check_db_staleness())",
  "",
  ".BREAKING_CHANGES_DB <- list(",
  ""
)

body <- character(0)

for (pkg in pkgs) {
  pkg_keys <- names(grouped)[startsWith(names(grouped), paste0(pkg, "::"))]
  if (length(pkg_keys) == 0L) next

  sep <- paste(rep("-", max(1L, 67L - nchar(pkg))), collapse = "")
  body <- c(body, sprintf("  # ---- %s %s", pkg, sep), "")

  for (ki in seq_along(pkg_keys)) {
    key <- pkg_keys[[ki]]
    group <- grouped[[key]]
    fn <- group[[1L]]$fn

    is_last <- (pkg == pkgs[length(pkgs)]) && (ki == length(pkg_keys))
    key_end <- if (is_last) "  )" else "  ),"

    body <- c(body, sprintf('  "%s::%s" = list(', pkg, fn))

    for (i in seq_along(group)) {
      comma <- if (i < length(group)) "," else ""
      body <- c(body, emit_entry(group[[i]], comma))
    }
    body <- c(body, key_end, "")
  }
}

footer <- c(
  ")",
  "",
  "# ---- internal helpers ---------------------------------------------------",
  "",
  "#' List all keys in the breaking-changes database",
  "#' @noRd",
  ".list_db_keys <- function() names(.BREAKING_CHANGES_DB)",
  "",
  "#' Get breaking-change entries for a pkg::fn key",
  "#' @noRd",
  ".get_breaking_changes <- function(key) .BREAKING_CHANGES_DB[[key]]",
  ""
)

out_lines <- c(header, body, footer)

# ---- Write and verify -------------------------------------------------------

out_path <- "R/breaking_changes_db.R"
writeLines(out_lines, out_path)
cat(sprintf("\nWritten %d lines to %s\n", length(out_lines), out_path))

# Verify it parses
tryCatch(
  {
    source(out_path, local = TRUE)
    n_keys <- length(get(".list_db_keys", envir = environment())())
    cat(sprintf("Verified: %d pkg::fn keys load cleanly\n", n_keys))
  },
  error = function(e) {
    stop("Generated file fails to parse: ", conditionMessage(e))
  }
)
