# Breaking changes database for reproducr
#
# AUTO-GENERATED by data-raw/sync_db.R -- do not edit by hand.
# Source of truth: https://github.com/repro-stats/reproducr-db
#
# Generated: 2026-06-11 14:00 UTC
# Entries:   32 across 32 pkg::fn keys
#
# Schema per entry:
#   from_version : last safe version (exclusive lower bound)
#   to_version   : last risky version (inclusive upper bound)
#   risk         : 'high' | 'medium' | 'low'
#   description  : plain-English explanation
#   reference    : URL to official changelog
#   closed       : TRUE if window is intentionally closed
#                  (skipped by check_db_staleness())

.BREAKING_CHANGES_DB <- list(

  # ---- broom --------------------------------------------------------------

  "broom::tidy" = list(
    list(
      from_version = "0.7.99",
      to_version   = "1.0.13",
      risk         = "medium",
      description  = paste0(
        "In broom 0.8.0, tidy() renamed columns for several model",
        "types (e.g. 'statistic' became 'z' for glm). Code selecting",
        "columns by name from tidy() output will silently select",
        "wrong columns or error."
      ),
      reference = "https://broom.tidymodels.org/news/index.html"
    )
  ),

  # ---- cobalt -------------------------------------------------------------

  "cobalt::bal.tab" = list(
    list(
      from_version = "4.2.99",
      to_version   = "4.6.9",
      risk         = "medium",
      description  = paste0(
        "In cobalt 4.3.0, bal.tab() changed the default display of",
        "the original function call: it is now hidden by default",
        "(disp.call = FALSE). Code that parses the printed output of",
        "bal.tab() to extract balance statistics, or that relies on",
        "the call being displayed, will produce different results.",
        "The Balance column name structure also changed for some",
        "covariate types."
      ),
      reference = "https://ngreifer.github.io/cobalt/news/index.html"
    )
  ),

  # ---- data.table ---------------------------------------------------------

  "data.table::fread" = list(
    list(
      from_version = "1.13.99",
      to_version   = "1.18.9",
      risk         = "medium",
      description  = paste0(
        "In data.table 1.14.0, fread() improved column type",
        "detection, which may cause some columns to parse",
        "differently. Specify colClasses explicitly to guarantee",
        "consistent ingestion across versions."
      ),
      reference = "https://github.com/Rdatatable/data.table/blob/master/NEWS.md"
    )
  ),

  "data.table::melt" = list(
    list(
      from_version = "1.13.99",
      to_version   = "1.18.9",
      risk         = "low",
      description  = paste0(
        "In data.table 1.14.0, melt() changed the default class of",
        "the 'variable' column from factor to character. Code that",
        "uses factor levels from the variable column will silently",
        "fail or produce different orderings."
      ),
      reference = "https://github.com/Rdatatable/data.table/blob/master/NEWS.md"
    )
  ),

  # ---- dplyr --------------------------------------------------------------

  "dplyr::across" = list(
    list(
      from_version = "1.0.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In dplyr 1.1.0, across() changed column naming when .names",
        "uses the {col}_{fn} pattern with multiple functions. The",
        "function label changed from the function name to the",
        "list-element name. Column names in output data frames may",
        "differ silently."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-110"
    )
  ),

  "dplyr::filter" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In dplyr 1.0.8, filter() began forbidding matrix results",
        "and warning about data frame results -- particularly data",
        "frames produced by across(), which previously could be",
        "silently used as filter conditions. Code using",
        "filter(across(...)) without if_any()/if_all() may now warn",
        "or error where it previously ran silently."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-108"
    )
  ),

  "dplyr::group_by" = list(
    list(
      from_version = "1.0.99",
      to_version   = "1.1.9",
      risk         = "medium",
      description  = paste0(
        "In dplyr 1.1.0, arrange() and group_by() changed to order",
        "character vectors using the C locale instead of the system",
        "locale. Code that groups or sorts by character columns",
        "(especially with accented characters or mixed case) may",
        "silently produce a different row order than under dplyr",
        "1.0.x. Set options(dplyr.legacy_locale = TRUE) to revert,",
        "or use arrange(.locale = ) to control explicitly."
      ),
      reference = "https://dplyr.tidyverse.org/reference/group_by.html"
    )
  ),

  "dplyr::mutate" = list(
    list(
      from_version = "1.0.99",
      to_version   = "1.2.9",
      risk         = "low",
      description  = paste0(
        "In dplyr 1.1.0, mutate() gained a .by argument as an",
        "alternative to group_by(). Existing code is unaffected, but",
        "per-operation grouping via .by does not retain grouping in",
        "the result."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-110"
    )
  ),

  # ---- ggplot2 ------------------------------------------------------------

  "ggplot2::geom_histogram" = list(
    list(
      from_version = "3.5.99",
      to_version   = "4.0.9",
      risk         = "medium",
      description  = paste0(
        "In ggplot2 4.0.0, all binning stats (including",
        "geom_histogram()/stat_bin()) switched to a boundary/center",
        "parametrisation rather than origin, and the default",
        "boundary is now chosen to better adhere to the nbin",
        "argument. This may silently change the bin edges and",
        "resulting bar positions/heights of histograms that rely on",
        "default binning, with no code change required."
      ),
      reference = "https://ggplot2.tidyverse.org/news/index.html#ggplot2-400"
    )
  ),

  "ggplot2::geom_sf" = list(
    list(
      from_version = "3.3.99",
      to_version   = "3.4.9",
      risk         = "low",
      description  = paste0(
        "In ggplot2 3.4.0, geom_sf()'s default polygon border",
        "linewidth changed from 0.5 to 0.2 (this geom continues to",
        "use the size aesthetic for points, unlike most other geoms",
        "which switched to linewidth). Separately, a switch from",
        "digest::digest() to rlang::hash() for internal hashing may",
        "change the automatic ordering of legends. Both changes are",
        "maintainer-acknowledged silent visual changes: saved",
        "maps/plots generated after upgrading may show thinner",
        "polygon borders and/or differently-ordered legend entries",
        "with no code change."
      ),
      reference = "https://tidyverse.org/blog/2022/11/ggplot2-3-4-0/"
    )
  ),

  "ggplot2::scale_colour_continuous" = list(
    list(
      from_version = "3.5.99",
      to_version   = "4.0.9",
      risk         = "low",
      description  = paste0(
        "In ggplot2 4.0.0, the default colour and fill scales gained",
        "a palette argument; the new default (palette = NULL)",
        "retrieves palettes from the active theme rather than using",
        "a hardcoded default, and this is now the default for",
        "generic scales like",
        "scale_colour_continuous()/scale_fill_continuous(). Plots",
        "using a customised theme palette setting",
        "(theme(palette.colour.continuous = ...) or similar) may now",
        "silently receive different default colours than under",
        "ggplot2 3.5.x, even without changing scale calls."
      ),
      reference = "https://ggplot2.tidyverse.org/news/index.html#ggplot2-400"
    )
  ),

  # ---- lme4 ---------------------------------------------------------------

  "lme4::lmer" = list(
    list(
      from_version = "1.1.28",
      to_version   = "2.0.9",
      risk         = "low",
      description  = paste0(
        "Between lme4 1.1.29 and 1.1.30, default optimizer",
        "tolerances were adjusted. Borderline models may converge to",
        "slightly different parameter estimates. Results are",
        "typically equivalent within rounding, but exact",
        "reproduction requires pinning the lme4 version."
      ),
      reference = "https://cran.r-project.org/web/packages/lme4/news/news.html"
    )
  ),

  # ---- lubridate ----------------------------------------------------------

  "lubridate::period" = list(
    list(
      from_version = "1.8.99",
      to_version   = "1.9.9",
      risk         = "medium",
      description  = paste0(
        "In lubridate 1.9.0, period() and duration arithmetic",
        "revised timezone and DST handling. Date calculations that",
        "span daylight-saving boundaries may return different",
        "results."
      ),
      reference = "https://lubridate.tidyverse.org/news/index.html"
    )
  ),

  "lubridate::ymd" = list(
    list(
      from_version = "1.8.99",
      to_version   = "1.9.9",
      risk         = "low",
      description  = paste0(
        "In lubridate 1.9.0, date-parsing functions (ymd, mdy, dmy,",
        "etc.) improved handling of ambiguous formats. Previously",
        "silently-parsed dates may now fail or parse differently."
      ),
      reference = "https://lubridate.tidyverse.org/news/index.html"
    )
  ),

  # ---- MatchIt ------------------------------------------------------------

  "MatchIt::match.data" = list(
    list(
      from_version = "4.4.99",
      to_version   = "4.7.9",
      risk         = "medium",
      description  = paste0(
        "In MatchIt 4.5.0, match.data() gained a subclass column in",
        "its output for all matching methods, not just",
        "subclassification. Code that assumes a fixed column",
        "structure in the matched dataset (e.g., column indexing or",
        "merging by position) may silently include an unexpected",
        "column or produce incorrect joins."
      ),
      reference = "https://kosukeimai.github.io/MatchIt/news/index.html"
    )
  ),

  "MatchIt::matchit" = list(
    list(
      from_version = "4.6.99",
      to_version = "4.7.9",
      risk = "high",
      description = paste0(
        "In MatchIt 4.0.0, the package was completely rewritten. The",
        "distance argument changed syntax: the old default distance",
        "= 'logit' is now distance = 'glm', link = 'logit'. The",
        "output object structure changed substantially --",
        "match.matrix, subclass, and weights components differ from",
        "3.x. Code that accesses matchit() output directly by",
        "component name may silently return wrong values or error."
      ),
      reference = "https://kosukeimai.github.io/MatchIt/news/index.html"
    )
  ),

  # ---- purrr --------------------------------------------------------------

  "purrr::map_df" = list(
    list(
      from_version = "0.3.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In purrr 1.0.0, map_df() was soft-deprecated in favour of",
        "map() |> list_rbind(). Behaviour may differ for edge cases",
        "involving NULL elements or varying column structures."
      ),
      reference = "https://purrr.tidyverse.org/news/index.html"
    )
  ),

  # ---- readr --------------------------------------------------------------

  "readr::read_csv" = list(
    list(
      from_version = "1.4.99",
      to_version   = "2.2.9",
      risk         = "medium",
      description  = paste0(
        "In readr 2.0.0, the second-edition (vroom-based) parsing",
        "engine changed how length>1 character vectors are",
        "interpreted: previously treated as literal data to parse,",
        "they are now assumed to be multiple file paths. Code",
        "passing literal CSV text as a length>1 character vector",
        "(e.g. multiple lines built with c()) may silently be",
        "interpreted as a list of filenames instead of being parsed",
        "as data. Wrap literal data in I() to preserve the old",
        "behaviour; readr only began warning about un-I()'d literal",
        "data in 2.2.0."
      ),
      reference = "https://readr.tidyverse.org/news/index.html#readr-200"
    )
  ),

  "readr::read_tsv" = list(
    list(
      from_version = "1.4.99",
      to_version   = "2.2.9",
      risk         = "medium",
      description  = paste0(
        "In readr 2.0.0, the second-edition (vroom-based) parsing",
        "engine changed how length>1 character vectors are",
        "interpreted: previously treated as literal data to parse,",
        "they are now assumed to be multiple file paths. Code",
        "passing literal CSV text as a length>1 character vector",
        "(e.g. multiple lines built with c()) may silently be",
        "interpreted as a list of filenames instead of being parsed",
        "as data. Wrap literal data in I() to preserve the old",
        "behaviour; readr only began warning about un-I()'d literal",
        "data in 2.2.0."
      ),
      reference = "https://readr.tidyverse.org/news/index.html#readr-200"
    )
  ),

  # ---- rstan --------------------------------------------------------------

  "rstan::extract" = list(
    list(
      from_version = "2.17.99",
      to_version   = "2.32.9",
      risk         = "medium",
      description  = paste0(
        "rstan::extract() defaults to permuted = TRUE, which merges",
        "and randomly permutes draws from all chains before",
        "returning them. Code that relies on draw order for",
        "convergence diagnostics, sequential analysis, or",
        "reproducible posterior summaries will produce different",
        "results across runs without explicit permuted = FALSE.",
        "Always specify the permuted argument explicitly."
      ),
      reference = "https://mc-stan.org/rstan/reference/stanfit-method-extract.html"
    )
  ),

  "rstan::stan" = list(
    list(
      from_version = "2.21.99",
      to_version   = "2.32.9",
      risk         = "high",
      description  = paste0(
        "In rstan 2.26, Stan introduced a new array declaration",
        "syntax. The old syntax (e.g. 'real x[N]') is deprecated and",
        "removed in Stan 2.33. Models compiled with rstan < 2.26",
        "using old syntax may fail to compile or produce unexpected",
        "results with rstan >= 2.26. Update Stan model code to the",
        "new array syntax: 'array[N] real x'."
      ),
      reference = "https://mc-stan.org/docs/reference-manual/postfix-brackets-array-syntax.html"
    )
  ),

  # ---- stats --------------------------------------------------------------

  "stats::hclust" = list(
    list(
      from_version = "3.6.99",
      to_version   = "4.0.9",
      risk         = "high",
      description  = paste0(
        "In R 4.0.0, hclust() changed its tie-breaking rule for",
        "equal distances. Dendrograms for datasets with tied",
        "distance values will differ between R 3.x and R 4.x."
      ),
      reference    = "https://cran.r-project.org/doc/manuals/r-release/NEWS.html",
      closed       = TRUE
    )
  ),

  "stats::rbinom" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Results from rbinom()",
        "with the same seed will differ between R <= 3.5 and R >=",
        "3.6."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  "stats::rnorm" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Stochastic output from",
        "rnorm() with the same seed will differ between R <= 3.5 and",
        "R >= 3.6."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  "stats::runif" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Stochastic output from",
        "runif() with the same seed will differ between R <= 3.5 and",
        "R >= 3.6. Use set.seed() with explicit kind argument for",
        "stable results."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  "stats::sample" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, the default RNG algorithm for sample() changed",
        "(sample.kind = 'Rejection' replaced 'Rounding'). Results",
        "produced with the same seed in R <= 3.5 will differ in R >=",
        "3.6. Use set.seed(seed, kind = 'Mersenne-Twister',",
        "sample.kind = 'Rejection') for explicit reproducibility."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  # ---- stringr ------------------------------------------------------------

  "stringr::str_c" = list(
    list(
      from_version = "1.4.99",
      to_version   = "1.6.9",
      risk         = "high",
      description  = paste0(
        "In stringr 1.5.0, str_c() changed NA handling to match base",
        "paste(): str_c('a', NA) now returns NA instead of 'aNa'.",
        "Code that relied on the old behaviour to build strings",
        "containing 'NA' will silently produce different",
        "(NA-propagating) results."
      ),
      reference = "https://stringr.tidyverse.org/news/index.html"
    )
  ),

  # ---- survival -----------------------------------------------------------

  "survival::coxph" = list(
    list(
      from_version = "3.1.99",
      to_version   = "3.8.9",
      risk         = "low",
      description  = paste0(
        "In survival 3.2.0, coxph() updated its default handling of",
        "the robust variance estimator for weighted models. Models",
        "with non-integer weights (e.g., IPTW or matching weights)",
        "may return slightly different standard errors and",
        "confidence intervals compared to survival 3.1.x. The change",
        "is small but affects exact numerical reproducibility."
      ),
      reference = "https://cran.r-project.org/web/packages/survival/news/news.html"
    )
  ),

  "survival::survfit" = list(
    list(
      from_version = "2.99.99",
      to_version   = "3.8.9",
      risk         = "medium",
      description  = paste0(
        "In survival 3.0.0, survfit() changed its output object",
        "structure. The $surv, $time, and $n.event components now",
        "always return matrices for multi-strata fits rather than",
        "vectors. Code that accesses survfit() output with numeric",
        "indexing (e.g., $surv[1]) will silently return the wrong",
        "group's estimate when multiple strata are present."
      ),
      reference = "https://cran.r-project.org/web/packages/survival/news/news.html"
    )
  ),

  # ---- tidyr --------------------------------------------------------------

  "tidyr::nest" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.3.9",
      risk         = "high",
      description  = paste0(
        "In tidyr 1.0.0, nest() and unnest() were overhauled with",
        "new syntax: nest(x, y, z) became nest(data = c(x, y, z)),",
        "and the first argument changed from data to .data.",
        "Additionally, nest() now preserves grouping from",
        "dplyr::group_by(), which affects downstream group-aware",
        "calls like mutate() and filter(). Old positional-column",
        "usage of nest() generates a translation warning but may not",
        "always translate correctly, and code relying on nest()",
        "*not* preserving groups may now silently behave",
        "differently."
      ),
      reference = "https://rdrr.io/cran/tidyr/f/NEWS.md"
    )
  ),

  "tidyr::pivot_wider" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.3.9",
      risk         = "medium",
      description  = paste0(
        "tidyr 1.0.0 introduced pivot_wider() as a replacement for",
        "spread(). Unlike spread(), which silently kept the last",
        "value for duplicate identifier rows, pivot_wider() with the",
        "default values_fn = NULL produces list-columns (with a",
        "warning) when identifiers are not unique, rather than",
        "silently picking one value. Code migrated from spread() to",
        "pivot_wider() without specifying values_fn may now get",
        "list-columns or warnings instead of the previously silent",
        "last-value-wins behaviour. tidyr 1.2.0 further improved the",
        "diagnostic message shown in this situation."
      ),
      reference = "https://rdrr.io/cran/tidyr/f/NEWS.md"
    )
  ),

  "tidyr::unnest" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.3.9",
      risk         = "medium",
      description  = paste0(
        "In tidyr 1.0.0, unnest() was rewritten. The old interface",
        "(passing multiple columns positionally) changed; .drop and",
        ".id arguments were removed. Code using the old unnest() API",
        "may silently change structure."
      ),
      reference = "https://tidyr.tidyverse.org/news/index.html"
    )
  )

)

# ---- internal helpers ---------------------------------------------------

#' List all keys in the breaking-changes database
#' @noRd
.list_db_keys <- function() names(.BREAKING_CHANGES_DB)

#' Get breaking-change entries for a pkg::fn key
#' @noRd
.get_breaking_changes <- function(key) .BREAKING_CHANGES_DB[[key]]

