# Breaking changes database for reproducr
#
# AUTO-GENERATED by data-raw/sync_db.R — do not edit by hand.
# Source of truth: https://github.com/repro-stats/reproducr-db
#
# Generated: 2026-06-05 16:54 UTC
# Entries:   64 across 35 pkg::fn keys
#
# Schema per entry:
#   from_version : last safe version (exclusive lower bound)
#   to_version   : last risky version (inclusive upper bound)
#   risk         : 'high' | 'medium' | 'low'
#   description  : plain-English explanation
#   reference    : URL to official changelog
#   closed       : TRUE if window is intentionally closed
#                  (skipped by check_db_staleness())

.BREAKING_CHANGES_DB <- list(

  # ---- broom --------------------------------------------------------------

  "broom::tidy" = list(
    list(
      from_version = "0.7.99",
      to_version   = "1.0.13",
      risk         = "medium",
      description  = paste0(
        "In broom 0.8.0, tidy() renamed columns for several model",
        "types (e.g. 'statistic' became 'z' for glm). Code selecting",
        "columns by name from tidy() output will silently select",
        "wrong columns or error."
      ),
      reference = "https://broom.tidymodels.org/news/index.html"
    ),
    list(
      from_version = "0.7.99",
      to_version   = "1.0.9",
      risk         = "medium",
      description  = paste0(
        "In broom 0.8.0, tidy() renamed columns for several model",
        "types (e.g. 'statistic' became 'z' for glm). Code selecting",
        "columns by name from tidy() output will silently select",
        "wrong columns or error."
      ),
      reference = "https://broom.tidymodels.org/news/index.html"
    )
  ),

  # ---- caret --------------------------------------------------------------

  "caret::train" = list(
    list(
      from_version = "6.0.99",
      to_version   = "7.0.9",
      risk         = "medium",
      description  = paste0(
        "In caret 7.0.0, the train() function underwent significant",
        "interface changes including updated default resampling",
        "methods and model tuning behaviour. Results from caret 6.x",
        "models may not replicate exactly under caret 7.x without",
        "pinning the version and resampling seed."
      ),
      reference = "https://cran.r-project.org/web/packages/caret/news/news.html"
    )
  ),

  # ---- cobalt -------------------------------------------------------------

  "cobalt::bal.tab" = list(
    list(
      from_version = "4.2.99",
      to_version   = "4.6.9",
      risk         = "medium",
      description  = paste0(
        "In cobalt 4.3.0, bal.tab() changed the default display of",
        "the original function call: it is now hidden by default",
        "(disp.call = FALSE). Code that parses the printed output of",
        "bal.tab() to extract balance statistics, or that relies on",
        "the call being displayed, will produce different results.",
        "The Balance column name structure also changed for some",
        "covariate types."
      ),
      reference = "https://ngreifer.github.io/cobalt/news/index.html"
    )
  ),

  # ---- data.table ---------------------------------------------------------

  "data.table::fread" = list(
    list(
      from_version = "1.13.99",
      to_version   = "1.18.9",
      risk         = "medium",
      description  = paste0(
        "In data.table 1.14.0, fread() improved column type",
        "detection, which may cause some columns to parse",
        "differently. Specify colClasses explicitly to guarantee",
        "consistent ingestion across versions."
      ),
      reference = "https://github.com/Rdatatable/data.table/blob/master/NEWS.md"
    ),
    list(
      from_version = "1.13.99",
      to_version   = "1.15.9",
      risk         = "medium",
      description  = paste0(
        "In data.table 1.14.0, fread() improved column type",
        "detection, which may cause some columns to parse",
        "differently. Specify colClasses explicitly to guarantee",
        "consistent ingestion across versions."
      ),
      reference = "https://github.com/Rdatatable/data.table/blob/master/NEWS.md"
    )
  ),

  "data.table::melt" = list(
    list(
      from_version = "1.13.99",
      to_version   = "1.18.9",
      risk         = "low",
      description  = paste0(
        "In data.table 1.14.0, melt() changed the default class of",
        "the 'variable' column from factor to character. Code that",
        "uses factor levels from the variable column will silently",
        "fail or produce different orderings."
      ),
      reference = "https://github.com/Rdatatable/data.table/blob/master/NEWS.md"
    ),
    list(
      from_version = "1.13.99",
      to_version   = "1.15.9",
      risk         = "low",
      description  = paste0(
        "In data.table 1.14.0, melt() changed the default class of",
        "the 'variable' column from factor to character. Code that",
        "uses factor levels from the variable column will silently",
        "fail or produce different orderings."
      ),
      reference = "https://github.com/Rdatatable/data.table/blob/master/NEWS.md"
    )
  ),

  # ---- dplyr --------------------------------------------------------------

  "dplyr::across" = list(
    list(
      from_version = "1.0.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In dplyr 1.1.0, across() changed column naming when .names",
        "uses the {col}_{fn} pattern with multiple functions. The",
        "function label changed from the function name to the",
        "list-element name. Column names in output data frames may",
        "differ silently."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-110"
    ),
    list(
      from_version = "1.0.99",
      to_version   = "1.1.9",
      risk         = "medium",
      description  = paste0(
        "In dplyr 1.1.0, across() changed column naming when .names",
        "uses the {col}_{fn} pattern with multiple functions. The",
        "function label changed from the function name to the",
        "list-element name. Column names in output data frames may",
        "differ silently."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-110"
    )
  ),

  "dplyr::filter" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In dplyr 1.0.0, filter() began issuing warnings (later",
        "errors) when passed list inputs or non-logical vectors.",
        "Code using filter() with indirect conditions may silently",
        "return wrong rows or now error."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-100"
    ),
    list(
      from_version = "0.8.99",
      to_version   = "1.0.9",
      risk         = "medium",
      description  = paste0(
        "In dplyr 1.0.0, filter() began issuing warnings (later",
        "errors) when passed list inputs or non-logical vectors.",
        "Code using filter() with indirect conditions may silently",
        "return wrong rows or now error."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-100"
    )
  ),

  "dplyr::mutate" = list(
    list(
      from_version = "1.0.99",
      to_version   = "1.2.9",
      risk         = "low",
      description  = paste0(
        "In dplyr 1.1.0, mutate() gained a .by argument as an",
        "alternative to group_by(). Existing code is unaffected, but",
        "per-operation grouping via .by does not retain grouping in",
        "the result."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-110"
    ),
    list(
      from_version = "1.0.99",
      to_version   = "1.1.9",
      risk         = "low",
      description  = paste0(
        "In dplyr 1.1.0, mutate() gained a .by argument as an",
        "alternative to group_by(). Existing code is unaffected, but",
        "per-operation grouping via .by does not retain grouping in",
        "the result."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-110"
    )
  ),

  "dplyr::summarise" = list(
    list(
      from_version = "1.0.99",
      to_version   = "1.2.9",
      risk         = "high",
      description  = paste0(
        "In dplyr 1.1.0, summarise() changed its default grouping",
        "behaviour: it now drops the last grouping level and returns",
        "an ungrouped data frame by default (.groups = 'drop_last').",
        "Code that relied on the result being grouped (e.g. chaining",
        "further group operations without re-grouping) will produce",
        "silently different results."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-110"
    ),
    list(
      from_version = "1.0.99",
      to_version   = "1.1.9",
      risk         = "high",
      description  = paste0(
        "In dplyr 1.1.0, summarise() changed its default grouping",
        "behaviour: it now drops the last grouping level and returns",
        "an ungrouped data frame by default (.groups = 'drop_last').",
        "Code that relied on the result being grouped (e.g. chaining",
        "further group operations without re-grouping) will produce",
        "silently different results."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-110"
    )
  ),

  "dplyr::summarize" = list(
    list(
      from_version = "1.0.99",
      to_version   = "1.2.9",
      risk         = "high",
      description  = paste0(
        "In dplyr 1.1.0, summarize() changed its default grouping",
        "behaviour: it now drops the last grouping level by default",
        "(.groups = 'drop_last'). Code relying on retained grouping",
        "structure will produce different results."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-110"
    ),
    list(
      from_version = "1.0.99",
      to_version   = "1.1.9",
      risk         = "high",
      description  = paste0(
        "In dplyr 1.1.0, summarize() changed its default grouping",
        "behaviour: it now drops the last grouping level by default",
        "(.groups = 'drop_last'). Code relying on retained grouping",
        "structure will produce different results."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-110"
    )
  ),

  # ---- ggplot2 ------------------------------------------------------------

  "ggplot2::aes" = list(
    list(
      from_version = "3.4.99",
      to_version   = "3.5.9",
      risk         = "medium",
      description  = paste0(
        "In ggplot2 3.5.0, aes() tightened evaluation rules. Bare",
        "column names that previously resolved from the global",
        "environment now require explicit scoping. Code using",
        "non-standard evaluation patterns outside data may silently",
        "drop aesthetics or error."
      ),
      reference = "https://ggplot2.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "3.4.99",
      to_version   = "4.0.9",
      risk         = "medium",
      description  = paste0(
        "In ggplot2 3.5.0, aes() tightened evaluation rules. Bare",
        "column names that previously resolved from the global",
        "environment now require explicit scoping. Code using",
        "non-standard evaluation patterns outside data may silently",
        "drop aesthetics or error."
      ),
      reference = "https://ggplot2.tidyverse.org/news/index.html"
    )
  ),

  "ggplot2::geom_histogram" = list(
    list(
      from_version = "3.3.99",
      to_version   = "3.5.9",
      risk         = "low",
      description  = paste0(
        "In ggplot2 3.4.0, geom_histogram() improved its default",
        "binwidth selection algorithm. Visual output (bin",
        "boundaries, counts per bin) may differ slightly from",
        "earlier versions when binwidth is not specified."
      ),
      reference = "https://ggplot2.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "3.3.99",
      to_version   = "4.0.9",
      risk         = "low",
      description  = paste0(
        "In ggplot2 3.4.0, geom_histogram() improved its default",
        "binwidth selection algorithm. Visual output (bin",
        "boundaries, counts per bin) may differ slightly from",
        "earlier versions when binwidth is not specified."
      ),
      reference = "https://ggplot2.tidyverse.org/news/index.html"
    )
  ),

  "ggplot2::scale_colour_continuous" = list(
    list(
      from_version = "3.3.99",
      to_version   = "3.4.9",
      risk         = "low",
      description  = paste0(
        "In ggplot2 3.4.0, the default continuous colour scale",
        "changed from a blue gradient to a viridis-based scale.",
        "Saved plots and reports generated after upgrading will use",
        "different colours."
      ),
      reference = "https://ggplot2.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "3.3.99",
      to_version   = "4.0.9",
      risk         = "low",
      description  = paste0(
        "In ggplot2 3.4.0, the default continuous colour scale",
        "changed from a blue gradient to a viridis-based scale.",
        "Saved plots and reports generated after upgrading will use",
        "different colours."
      ),
      reference = "https://ggplot2.tidyverse.org/news/index.html"
    )
  ),

  # ---- lme4 ---------------------------------------------------------------

  "lme4::lmer" = list(
    list(
      from_version = "1.1.28",
      to_version   = "1.1.35",
      risk         = "low",
      description  = paste0(
        "Between lme4 1.1.29 and 1.1.30, default optimizer",
        "tolerances were adjusted. Borderline models may converge to",
        "slightly different parameter estimates. Results are",
        "typically equivalent within rounding, but exact",
        "reproduction requires pinning the lme4 version."
      ),
      reference = "https://cran.r-project.org/web/packages/lme4/news/news.html"
    ),
    list(
      from_version = "1.1.28",
      to_version   = "2.0.9",
      risk         = "low",
      description  = paste0(
        "Between lme4 1.1.29 and 1.1.30, default optimizer",
        "tolerances were adjusted. Borderline models may converge to",
        "slightly different parameter estimates. Results are",
        "typically equivalent within rounding, but exact",
        "reproduction requires pinning the lme4 version."
      ),
      reference = "https://cran.r-project.org/web/packages/lme4/news/news.html"
    )
  ),

  # ---- lubridate ----------------------------------------------------------

  "lubridate::period" = list(
    list(
      from_version = "1.8.99",
      to_version   = "1.9.9",
      risk         = "medium",
      description  = paste0(
        "In lubridate 1.9.0, period() and duration arithmetic",
        "revised timezone and DST handling. Date calculations that",
        "span daylight-saving boundaries may return different",
        "results."
      ),
      reference = "https://lubridate.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "1.8.99",
      to_version   = "1.9.9",
      risk         = "medium",
      description  = paste0(
        "In lubridate 1.9.0, period() and duration arithmetic",
        "revised timezone and DST handling. Date calculations that",
        "span daylight-saving boundaries may return different",
        "results."
      ),
      reference = "https://lubridate.tidyverse.org/news/index.html"
    )
  ),

  "lubridate::ymd" = list(
    list(
      from_version = "1.8.99",
      to_version   = "1.9.9",
      risk         = "low",
      description  = paste0(
        "In lubridate 1.9.0, date-parsing functions (ymd, mdy, dmy,",
        "etc.) improved handling of ambiguous formats. Previously",
        "silently-parsed dates may now fail or parse differently."
      ),
      reference = "https://lubridate.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "1.8.99",
      to_version   = "1.9.9",
      risk         = "low",
      description  = paste0(
        "In lubridate 1.9.0, date-parsing functions (ymd, mdy, dmy,",
        "etc.) improved handling of ambiguous formats. Previously",
        "silently-parsed dates may now fail or parse differently."
      ),
      reference = "https://lubridate.tidyverse.org/news/index.html"
    )
  ),

  # ---- MatchIt ------------------------------------------------------------

  "MatchIt::match.data" = list(
    list(
      from_version = "4.4.99",
      to_version   = "4.7.9",
      risk         = "medium",
      description  = paste0(
        "In MatchIt 4.5.0, match.data() gained a subclass column in",
        "its output for all matching methods, not just",
        "subclassification. Code that assumes a fixed column",
        "structure in the matched dataset (e.g., column indexing or",
        "merging by position) may silently include an unexpected",
        "column or produce incorrect joins."
      ),
      reference = "https://kosukeimai.github.io/MatchIt/news/index.html"
    )
  ),

  "MatchIt::matchit" = list(
    list(
      from_version = "3.0.2",
      to_version   = "4.7.9",
      risk         = "high",
      description  = paste0(
        "In MatchIt 4.0.0, the package was completely rewritten. The",
        "distance argument changed syntax: the old default distance",
        "= 'logit' is now distance = 'glm', link = 'logit'. The",
        "output object structure changed substantially —",
        "match.matrix, subclass, and weights components differ from",
        "3.x. Code that accesses matchit() output directly by",
        "component name may silently return wrong values or error."
      ),
      reference = "https://kosukeimai.github.io/MatchIt/news/index.html"
    )
  ),

  # ---- purrr --------------------------------------------------------------

  "purrr::map" = list(
    list(
      from_version = "0.3.99",
      to_version   = "1.0.9",
      risk         = "medium",
      description  = paste0(
        "In purrr 1.0.0, map() changed error handling: it now errors",
        "on missing elements and .default was removed. Code relying",
        "on silent NULL returns for missing elements will now fail",
        "or produce different results."
      ),
      reference = "https://purrr.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "0.3.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In purrr 1.0.0, map() changed error handling: it now errors",
        "on missing elements and .default was removed. Code relying",
        "on silent NULL returns for missing elements will now fail",
        "or produce different results."
      ),
      reference = "https://purrr.tidyverse.org/news/index.html"
    )
  ),

  "purrr::map_df" = list(
    list(
      from_version = "0.3.99",
      to_version   = "1.0.9",
      risk         = "medium",
      description  = paste0(
        "In purrr 1.0.0, map_df() was soft-deprecated in favour of",
        "map() |> list_rbind(). Behaviour may differ for edge cases",
        "involving NULL elements or varying column structures."
      ),
      reference = "https://purrr.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "0.3.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In purrr 1.0.0, map_df() was soft-deprecated in favour of",
        "map() |> list_rbind(). Behaviour may differ for edge cases",
        "involving NULL elements or varying column structures."
      ),
      reference = "https://purrr.tidyverse.org/news/index.html"
    )
  ),

  # ---- readr --------------------------------------------------------------

  "readr::read_csv" = list(
    list(
      from_version = "1.4.99",
      to_version   = "2.1.9",
      risk         = "high",
      description  = paste0(
        "In readr 2.0.0, read_csv() switched from a custom parser to",
        "the vroom backend. Column type guessing improved but",
        "changed: previously numeric columns may now parse as",
        "character (or vice versa) depending on the data. Always",
        "specify col_types explicitly for reproducible ingestion."
      ),
      reference = "https://readr.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "1.4.99",
      to_version   = "2.2.9",
      risk         = "high",
      description  = paste0(
        "In readr 2.0.0, read_csv() switched from a custom parser to",
        "the vroom backend. Column type guessing improved but",
        "changed: previously numeric columns may now parse as",
        "character (or vice versa) depending on the data. Always",
        "specify col_types explicitly for reproducible ingestion."
      ),
      reference = "https://readr.tidyverse.org/news/index.html"
    )
  ),

  "readr::read_tsv" = list(
    list(
      from_version = "1.4.99",
      to_version   = "2.1.9",
      risk         = "high",
      description  = paste0(
        "In readr 2.0.0, read_tsv() switched to the vroom backend.",
        "Column type guessing changed; results may differ. Specify",
        "col_types explicitly."
      ),
      reference = "https://readr.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "1.4.99",
      to_version   = "2.2.9",
      risk         = "high",
      description  = paste0(
        "In readr 2.0.0, read_tsv() switched to the vroom backend.",
        "Column type guessing changed; results may differ. Specify",
        "col_types explicitly."
      ),
      reference = "https://readr.tidyverse.org/news/index.html"
    )
  ),

  # ---- rstan --------------------------------------------------------------

  "rstan::extract" = list(
    list(
      from_version = "2.17.99",
      to_version   = "2.32.9",
      risk         = "medium",
      description  = paste0(
        "rstan::extract() defaults to permuted = TRUE, which merges",
        "and randomly permutes draws from all chains before",
        "returning them. Code that relies on draw order for",
        "convergence diagnostics, sequential analysis, or",
        "reproducible posterior summaries will produce different",
        "results across runs without explicit permuted = FALSE.",
        "Always specify the permuted argument explicitly."
      ),
      reference = "https://mc-stan.org/rstan/reference/stanfit-method-extract.html"
    ),
    list(
      from_version = "2.17.99",
      to_version   = "2.32.9",
      risk         = "medium",
      description  = paste0(
        "rstan::extract() defaults to permuted = TRUE, which merges",
        "and randomly permutes draws from all chains before",
        "returning them. Code that relies on draw order for",
        "convergence diagnostics, sequential analysis, or",
        "reproducible posterior summaries will produce different",
        "results across runs without explicit permuted = FALSE.",
        "Always specify the permuted argument explicitly."
      ),
      reference = "https://mc-stan.org/rstan/reference/stanfit-method-extract.html"
    )
  ),

  "rstan::stan" = list(
    list(
      from_version = "2.21.99",
      to_version   = "2.32.9",
      risk         = "high",
      description  = paste0(
        "In rstan 2.26, Stan introduced a new array declaration",
        "syntax. The old syntax (e.g. 'real x[N]') is deprecated and",
        "removed in Stan 2.33. Models compiled with rstan < 2.26",
        "using old syntax may fail to compile or produce unexpected",
        "results with rstan >= 2.26. Update Stan model code to the",
        "new array syntax: 'array[N] real x'."
      ),
      reference = "https://mc-stan.org/docs/reference-manual/postfix-brackets-array-syntax.html"
    ),
    list(
      from_version = "2.21.99",
      to_version   = "2.32.9",
      risk         = "high",
      description  = paste0(
        "In rstan 2.26, Stan introduced a new array declaration",
        "syntax. The old syntax (e.g. 'real x[N]') is deprecated and",
        "removed in Stan 2.33. Models compiled with rstan < 2.26",
        "using old syntax may fail to compile or produce unexpected",
        "results with rstan >= 2.26. Update Stan model code to the",
        "new array syntax: 'array[N] real x'."
      ),
      reference = "https://mc-stan.org/docs/reference-manual/postfix-brackets-array-syntax.html"
    )
  ),

  # ---- stats --------------------------------------------------------------

  "stats::hclust" = list(
    list(
      from_version = "3.6.99",
      to_version   = "4.0.9",
      risk         = "high",
      description  = paste0(
        "In R 4.0.0, hclust() changed its tie-breaking rule for",
        "equal distances. Dendrograms for datasets with tied",
        "distance values will differ between R 3.x and R 4.x."
      ),
      reference = "https://cran.r-project.org/doc/manuals/r-release/NEWS.html"
    ),
    list(
      from_version = "3.6.99",
      to_version   = "4.0.9",
      risk         = "high",
      description  = paste0(
        "In R 4.0.0, hclust() changed its tie-breaking rule for",
        "equal distances. Dendrograms for datasets with tied",
        "distance values will differ between R 3.x and R 4.x."
      ),
      reference    = "https://cran.r-project.org/doc/manuals/r-release/NEWS.html",
      closed       = TRUE
    )
  ),

  "stats::rbinom" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Results from rbinom()",
        "with the same seed will differ between R <= 3.5 and R >=",
        "3.6."
      ),
      reference = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html"
    ),
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Results from rbinom()",
        "with the same seed will differ between R <= 3.5 and R >=",
        "3.6."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  "stats::rnorm" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Stochastic output from",
        "rnorm() with the same seed will differ between R <= 3.5 and",
        "R >= 3.6."
      ),
      reference = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html"
    ),
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Stochastic output from",
        "rnorm() with the same seed will differ between R <= 3.5 and",
        "R >= 3.6."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  "stats::runif" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Stochastic output from",
        "runif() with the same seed will differ between R <= 3.5 and",
        "R >= 3.6. Use set.seed() with explicit kind argument for",
        "stable results."
      ),
      reference = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html"
    ),
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Stochastic output from",
        "runif() with the same seed will differ between R <= 3.5 and",
        "R >= 3.6. Use set.seed() with explicit kind argument for",
        "stable results."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  "stats::sample" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, the default RNG algorithm for sample() changed",
        "(sample.kind = 'Rejection' replaced 'Rounding'). Results",
        "produced with the same seed in R <= 3.5 will differ in R >=",
        "3.6. Use set.seed(seed, kind = 'Mersenne-Twister',",
        "sample.kind = 'Rejection') for explicit reproducibility."
      ),
      reference = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html"
    ),
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, the default RNG algorithm for sample() changed",
        "(sample.kind = 'Rejection' replaced 'Rounding'). Results",
        "produced with the same seed in R <= 3.5 will differ in R >=",
        "3.6. Use set.seed(seed, kind = 'Mersenne-Twister',",
        "sample.kind = 'Rejection') for explicit reproducibility."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  # ---- stringr ------------------------------------------------------------

  "stringr::str_c" = list(
    list(
      from_version = "1.4.99",
      to_version   = "1.5.9",
      risk         = "high",
      description  = paste0(
        "In stringr 1.5.0, str_c() changed NA handling to match base",
        "paste(): str_c('a', NA) now returns NA instead of 'aNa'.",
        "Code that relied on the old behaviour to build strings",
        "containing 'NA' will silently produce different",
        "(NA-propagating) results."
      ),
      reference = "https://stringr.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "1.4.99",
      to_version   = "1.6.9",
      risk         = "high",
      description  = paste0(
        "In stringr 1.5.0, str_c() changed NA handling to match base",
        "paste(): str_c('a', NA) now returns NA instead of 'aNa'.",
        "Code that relied on the old behaviour to build strings",
        "containing 'NA' will silently produce different",
        "(NA-propagating) results."
      ),
      reference = "https://stringr.tidyverse.org/news/index.html"
    )
  ),

  # ---- survival -----------------------------------------------------------

  "survival::coxph" = list(
    list(
      from_version = "3.1.99",
      to_version   = "3.8.9",
      risk         = "low",
      description  = paste0(
        "In survival 3.2.0, coxph() updated its default handling of",
        "the robust variance estimator for weighted models. Models",
        "with non-integer weights (e.g., IPTW or matching weights)",
        "may return slightly different standard errors and",
        "confidence intervals compared to survival 3.1.x. The change",
        "is small but affects exact numerical reproducibility."
      ),
      reference = "https://cran.r-project.org/web/packages/survival/news/news.html"
    )
  ),

  "survival::survfit" = list(
    list(
      from_version = "2.99.99",
      to_version   = "3.8.9",
      risk         = "medium",
      description  = paste0(
        "In survival 3.0.0, survfit() changed its output object",
        "structure. The $surv, $time, and $n.event components now",
        "always return matrices for multi-strata fits rather than",
        "vectors. Code that accesses survfit() output with numeric",
        "indexing (e.g., $surv[1]) will silently return the wrong",
        "group's estimate when multiple strata are present."
      ),
      reference = "https://cran.r-project.org/web/packages/survival/news/news.html"
    )
  ),

  # ---- tidyr --------------------------------------------------------------

  "tidyr::nest" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.1.9",
      risk         = "high",
      description  = paste0(
        "In tidyr 1.0.0, nest() changed its interface: the by_",
        "argument was replaced with a tidyselect interface. Old code",
        "using nest(data, by_col) will either error or silently nest",
        "by the wrong columns."
      ),
      reference = "https://tidyr.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "0.8.99",
      to_version   = "1.3.9",
      risk         = "high",
      description  = paste0(
        "In tidyr 1.0.0, nest() changed its interface: the by_",
        "argument was replaced with a tidyselect interface. Old code",
        "using nest(data, by_col) will either error or silently nest",
        "by the wrong columns."
      ),
      reference = "https://tidyr.tidyverse.org/news/index.html"
    )
  ),

  "tidyr::pivot_wider" = list(
    list(
      from_version = "1.1.99",
      to_version   = "1.3.9",
      risk         = "medium",
      description  = paste0(
        "In tidyr 1.2.0, pivot_wider() changed its handling of",
        "duplicate identifier rows: it now errors by default",
        "(values_fn = NULL) instead of silently selecting the last",
        "value. Analyses with duplicated keys will now fail rather",
        "than producing quietly incorrect wide tables."
      ),
      reference = "https://tidyr.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "1.1.99",
      to_version   = "1.3.9",
      risk         = "medium",
      description  = paste0(
        "In tidyr 1.2.0, pivot_wider() changed its handling of",
        "duplicate identifier rows: it now errors by default",
        "(values_fn = NULL) instead of silently selecting the last",
        "value. Analyses with duplicated keys will now fail rather",
        "than producing quietly incorrect wide tables."
      ),
      reference = "https://tidyr.tidyverse.org/news/index.html"
    )
  ),

  "tidyr::unnest" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.1.9",
      risk         = "medium",
      description  = paste0(
        "In tidyr 1.0.0, unnest() was rewritten. The old interface",
        "(passing multiple columns positionally) changed; .drop and",
        ".id arguments were removed. Code using the old unnest() API",
        "may silently change structure."
      ),
      reference = "https://tidyr.tidyverse.org/news/index.html"
    ),
    list(
      from_version = "0.8.99",
      to_version   = "1.3.9",
      risk         = "medium",
      description  = paste0(
        "In tidyr 1.0.0, unnest() was rewritten. The old interface",
        "(passing multiple columns positionally) changed; .drop and",
        ".id arguments were removed. Code using the old unnest() API",
        "may silently change structure."
      ),
      reference = "https://tidyr.tidyverse.org/news/index.html"
    )
  ),

  # ---- nlme --------------------------------------------------------------

  "nlme::lme" = list(
    list(
      from_version = "3.1.152",
      to_version   = "3.1.169",
      risk         = "medium",
      description  = paste0(
        "In nlme 3.1.153+, the default optimizer control parameters for lme() ",
        "were updated. Mixed models close to convergence boundaries may return ",
        "slightly different variance component estimates across versions. ",
        "Intermediate precision CV and random effect estimates are sensitive ",
        "to these changes."
      ),
      reference = "https://cran.r-project.org/web/packages/nlme/news/news.html"
    )
  )
)

# ---- internal helpers ---------------------------------------------------

#' List all keys in the breaking-changes database
#' @noRd
.list_db_keys <- function() names(.BREAKING_CHANGES_DB)

#' Get breaking-change entries for a pkg::fn key
#' @noRd
.get_breaking_changes <- function(key) .BREAKING_CHANGES_DB[[key]]

