# Breaking changes database for reproducr
#
# AUTO-GENERATED by data-raw/sync_db.R -- do not edit by hand.
# Source of truth: https://github.com/repro-stats/reproducr-db
#
# Generated: 2026-06-18 08:14 UTC
# Entries:   34 across 34 pkg::fn keys
#
# Schema per entry:
#   from_version : last safe version (exclusive lower bound)
#   to_version   : last risky version (inclusive upper bound)
#   risk         : 'high' | 'medium' | 'low'
#   description  : plain-English explanation
#   reference    : URL to official changelog
#   closed       : TRUE if window is intentionally closed
#                  (skipped by check_db_staleness())

.BREAKING_CHANGES_DB <- list(

  # ---- cobalt -------------------------------------------------------------

  "cobalt::bal.tab" = list(
    list(
      from_version = "4.3.99",
      to_version   = "4.6.9",
      risk         = "low",
      description  = paste0(
        "In cobalt 4.4.1, bal.tab() changed the default value of the",
        "disp.call argument from TRUE to FALSE, meaning the original",
        "balancing function call is now hidden in printed output by",
        "default. Code that parses the printed output of bal.tab()",
        "to extract or display the call will no longer see it",
        "without explicitly setting disp.call = TRUE. This affects",
        "only printed/console output, not the underlying bal.tab",
        "object."
      ),
      reference = "https://ngreifer.github.io/cobalt/news/index.html"
    )
  ),

  # ---- data.table ---------------------------------------------------------

  "data.table::fread" = list(
    list(
      from_version = "1.15.99",
      to_version   = "1.18.9",
      risk         = "low",
      description  = paste0(
        "In data.table 1.16.0, fread() changed its default decimal",
        "separator handling to dec='auto', which automatically",
        "detects whether the file uses '.' or ',' as the decimal",
        "separator. Files using comma-decimal notation (common in",
        "European/South American locales) that previously parsed",
        "numeric columns as character or silently incorrect values",
        "may now parse differently. Code that relied on fread() NOT",
        "auto-detecting comma decimals, or that post-processed",
        "character columns expecting the old behaviour, may see",
        "different output."
      ),
      reference = "https://github.com/Rdatatable/data.table/blob/master/NEWS.md"
    )
  ),

  "data.table::melt" = list(
    list(
      from_version = "1.13.99",
      to_version   = "1.18.9",
      risk         = "low",
      description  = paste0(
        "In data.table 1.14.0, melt() changed the default class of",
        "the 'variable' column from factor to character. Code that",
        "uses factor levels from the variable column will silently",
        "fail or produce different orderings."
      ),
      reference = "https://github.com/Rdatatable/data.table/blob/master/NEWS.md"
    )
  ),

  # ---- dplyr --------------------------------------------------------------

  "dplyr::filter" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In dplyr 1.0.8, filter() began forbidding matrix results",
        "and warning about data frame results -- particularly data",
        "frames produced by across(), which previously could be",
        "silently used as filter conditions. Code using",
        "filter(across(...)) without if_any()/if_all() may now warn",
        "or error where it previously ran silently."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-108"
    )
  ),

  "dplyr::group_by" = list(
    list(
      from_version = "1.0.99",
      to_version   = "1.2.1",
      risk         = "medium",
      description  = paste0(
        "In dplyr 1.1.0, character vector grouping columns in",
        "group_by() are now ordered in the C locale instead of the",
        "system locale, which can silently change the ordering of",
        "grouped results. The dplyr.legacy_locale escape hatch was",
        "soft-deprecated in 1.2.0, reinforcing that this change is",
        "permanent through the current release series."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html"
    )
  ),

  "dplyr::select" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In dplyr 1.0.0, select() switched to the tidyselect",
        "backend. Selecting columns via an external character vector",
        "without wrapping it in all_of() or any_of() now triggers",
        "ambiguous selection: if the variable name matches a column",
        "name the column wins, otherwise it is silently dropped.",
        "Code using select(df, my_vars) where my_vars is a character",
        "vector must be updated to select(df, all_of(my_vars)) for",
        "safe, reproducible column selection."
      ),
      reference = "https://dplyr.tidyverse.org/news/index.html#dplyr-100"
    )
  ),

  # ---- ggplot2 ------------------------------------------------------------

  "ggplot2::geom_histogram" = list(
    list(
      from_version = "3.5.99",
      to_version   = "4.0.9",
      risk         = "medium",
      description  = paste0(
        "In ggplot2 4.0.0, all binning stats (including",
        "geom_histogram()/stat_bin()) switched to a boundary/center",
        "parametrisation rather than origin, and the default",
        "boundary is now chosen to better adhere to the nbin",
        "argument. This may silently change the bin edges and",
        "resulting bar positions/heights of histograms that rely on",
        "default binning, with no code change required."
      ),
      reference = "https://ggplot2.tidyverse.org/news/index.html#ggplot2-400"
    )
  ),

  "ggplot2::geom_sf" = list(
    list(
      from_version = "3.3.99",
      to_version   = "3.4.9",
      risk         = "low",
      description  = paste0(
        "In ggplot2 3.4.0, geom_sf()'s default polygon border",
        "linewidth changed from 0.5 to 0.2 (this geom continues to",
        "use the size aesthetic for points, unlike most other geoms",
        "which switched to linewidth). Separately, a switch from",
        "digest::digest() to rlang::hash() for internal hashing may",
        "change the automatic ordering of legends. Both changes are",
        "maintainer-acknowledged silent visual changes: saved",
        "maps/plots generated after upgrading may show thinner",
        "polygon borders and/or differently-ordered legend entries",
        "with no code change."
      ),
      reference = "https://tidyverse.org/blog/2022/11/ggplot2-3-4-0/"
    )
  ),

  "ggplot2::scale_colour_continuous" = list(
    list(
      from_version = "3.5.99",
      to_version   = "4.0.9",
      risk         = "low",
      description  = paste0(
        "In ggplot2 4.0.0, the default colour and fill scales gained",
        "a palette argument; the new default (palette = NULL)",
        "retrieves palettes from the active theme rather than using",
        "a hardcoded default, and this is now the default for",
        "generic scales like",
        "scale_colour_continuous()/scale_fill_continuous(). Plots",
        "using a customised theme palette setting",
        "(theme(palette.colour.continuous = ...) or similar) may now",
        "silently receive different default colours than under",
        "ggplot2 3.5.x, even without changing scale calls."
      ),
      reference = "https://ggplot2.tidyverse.org/news/index.html#ggplot2-400"
    )
  ),

  "ggplot2::theme" = list(
    list(
      from_version = "3.4.99",
      to_version   = "4.0.9",
      risk         = "medium",
      description  = paste0(
        "In ggplot2 3.5.0, passing a numeric vector to",
        "legend.position inside theme() (e.g. theme(legend.position",
        "= c(0.8, 0.2))) was deprecated. The correct replacement is",
        "the new legend.position.inside argument:",
        "theme(legend.position.inside = c(0.8, 0.2)). Code using the",
        "old numeric form produces a once-per-session deprecation",
        "warning and may break in a future release. Plots with",
        "in-panel legend placement will silently produce different",
        "visual output or errors after upgrading without updating",
        "the theme() call."
      ),
      reference = "https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0-legends/"
    )
  ),

  # ---- lubridate ----------------------------------------------------------

  "lubridate::period" = list(
    list(
      from_version = "1.8.99",
      to_version   = "1.9.9",
      risk         = "medium",
      description  = paste0(
        "In lubridate 1.9.0, the internal timezone and DST",
        "computation engine switched from Google's CCTZ to the",
        "timechange package. Period and duration arithmetic that",
        "spans DST boundaries or involves ambiguous/gap times (e.g.",
        "adding months() or years() across a DST transition) may",
        "return different results than under lubridate 1.8.x. The",
        "change is most likely to affect code adding calendar units",
        "(months, years) to POSIXct objects in non-UTC timezones."
      ),
      reference = "https://lubridate.tidyverse.org/news/index.html"
    )
  ),

  # ---- MatchIt ------------------------------------------------------------

  "MatchIt::match.data" = list(
    list(
      from_version = "4.0.99",
      to_version   = "4.4.9",
      risk         = "medium",
      description  = paste0(
        "In MatchIt 4.1.0, match.data() began including a subclass",
        "column in its output for all matching methods when replace",
        "= FALSE (the default), not just for subclassification,",
        "optimal, and full matching as before. Code that assumes a",
        "fixed column structure in the matched dataset (e.g. column",
        "indexing by position or merging by column count) may",
        "silently include an unexpected 'subclass' column or produce",
        "incorrect joins."
      ),
      reference = "https://kosukeimai.github.io/MatchIt/news/index.html"
    )
  ),

  "MatchIt::matchit" = list(
    list(
      from_version = "4.6.99",
      to_version   = "4.7.9",
      risk         = "high",
      description  = paste0(
        "In MatchIt 4.0.0, the package was completely rewritten. The",
        "distance argument changed syntax: the old default distance",
        "= 'logit' is now distance = 'glm', link = 'logit'. The",
        "output object structure changed substantially --",
        "match.matrix, subclass, and weights components differ from",
        "3.x. Code that accesses matchit() output directly by",
        "component name may silently return wrong values or error."
      ),
      reference = "https://kosukeimai.github.io/MatchIt/news/index.html"
    )
  ),

  # ---- purrr --------------------------------------------------------------

  "purrr::map_df" = list(
    list(
      from_version = "0.3.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In purrr 1.0.0, map_df() was soft-deprecated in favour of",
        "map() |> list_rbind(). Behaviour may differ for edge cases",
        "involving NULL elements or varying column structures."
      ),
      reference = "https://purrr.tidyverse.org/news/index.html"
    )
  ),

  "purrr::map2" = list(
    list(
      from_version = "0.3.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In purrr 1.0.0, map2() adopted tidyverse recycling rules:",
        "only length-1 vectors are recycled; all others must have",
        "the same length. Code relying on implicit recycling of",
        "vectors whose length is a multiple of the other will now",
        "error. Additionally, map2() now recycles the names of its",
        "first input, which can produce differently-named output",
        "lists compared to purrr < 1.0.0."
      ),
      reference = "https://purrr.tidyverse.org/news/index.html#purrr-100"
    )
  ),

  "purrr::pmap" = list(
    list(
      from_version = "0.3.99",
      to_version   = "1.2.9",
      risk         = "medium",
      description  = paste0(
        "In purrr 1.0.0, pmap() adopted tidyverse recycling rules:",
        "only length-1 list elements are recycled; all others must",
        "have the same length. Code relying on implicit recycling of",
        "non-length-1 inputs will now error. The map_dfr() and",
        "map_dfc() variants were also superseded in 1.0.0 in favour",
        "of map() |> list_rbind() and map() |> list_cbind(); scripts",
        "using them will produce deprecation warnings and may break",
        "in a future release."
      ),
      reference = "https://purrr.tidyverse.org/news/index.html#purrr-100"
    )
  ),

  # ---- readr --------------------------------------------------------------

  "readr::read_csv" = list(
    list(
      from_version = "1.4.99",
      to_version   = "2.2.9",
      risk         = "medium",
      description  = paste0(
        "In readr 2.0.0, the second-edition (vroom-based) parsing",
        "engine changed how length>1 character vectors are",
        "interpreted: previously treated as literal data to parse,",
        "they are now assumed to be multiple file paths. Code",
        "passing literal CSV text as a length>1 character vector",
        "(e.g. multiple lines built with c()) may silently be",
        "interpreted as a list of filenames instead of being parsed",
        "as data. Wrap literal data in I() to preserve the old",
        "behaviour; readr only began warning about un-I()'d literal",
        "data in 2.2.0."
      ),
      reference = "https://readr.tidyverse.org/news/index.html#readr-200"
    )
  ),

  "readr::read_tsv" = list(
    list(
      from_version = "1.4.99",
      to_version   = "2.2.9",
      risk         = "medium",
      description  = paste0(
        "In readr 2.0.0, the second-edition (vroom-based) parsing",
        "engine changed how length>1 character vectors are",
        "interpreted: previously treated as literal data to parse,",
        "they are now assumed to be multiple file paths. Code",
        "passing literal CSV text as a length>1 character vector",
        "(e.g. multiple lines built with c()) may silently be",
        "interpreted as a list of filenames instead of being parsed",
        "as data. Wrap literal data in I() to preserve the old",
        "behaviour; readr only began warning about un-I()'d literal",
        "data in 2.2.0."
      ),
      reference = "https://readr.tidyverse.org/news/index.html#readr-200"
    )
  ),

  # ---- rstan --------------------------------------------------------------

  "rstan::stan" = list(
    list(
      from_version = "2.21.99",
      to_version   = "2.32.9",
      risk         = "high",
      description  = paste0(
        "In rstan 2.26, Stan introduced a new array declaration",
        "syntax. The old syntax (e.g. 'real x[N]') is deprecated and",
        "removed in Stan 2.33. Models compiled with rstan < 2.26",
        "using old syntax may fail to compile or produce unexpected",
        "results with rstan >= 2.26. Update Stan model code to the",
        "new array syntax: 'array[N] real x'."
      ),
      reference = "https://mc-stan.org/docs/reference-manual/postfix-brackets-array-syntax.html"
    )
  ),

  # ---- stats --------------------------------------------------------------

  "stats::hclust" = list(
    list(
      from_version = "3.6.99",
      to_version   = "4.0.9",
      risk         = "high",
      description  = paste0(
        "In R 4.0.0, hclust() changed its tie-breaking rule for",
        "equal distances. Dendrograms for datasets with tied",
        "distance values will differ between R 3.x and R 4.x."
      ),
      reference    = "https://cran.r-project.org/doc/manuals/r-release/NEWS.html",
      closed       = TRUE
    )
  ),

  "stats::rbinom" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Results from rbinom()",
        "with the same seed will differ between R <= 3.5 and R >=",
        "3.6."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  "stats::rnorm" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Stochastic output from",
        "rnorm() with the same seed will differ between R <= 3.5 and",
        "R >= 3.6."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  "stats::runif" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, RNG defaults changed. Stochastic output from",
        "runif() with the same seed will differ between R <= 3.5 and",
        "R >= 3.6. Use set.seed() with explicit kind argument for",
        "stable results."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  "stats::sample" = list(
    list(
      from_version = "3.5.99",
      to_version   = "3.6.9",
      risk         = "high",
      description  = paste0(
        "In R 3.6.0, the default RNG algorithm for sample() changed",
        "(sample.kind = 'Rejection' replaced 'Rounding'). Results",
        "produced with the same seed in R <= 3.5 will differ in R >=",
        "3.6. Use set.seed(seed, kind = 'Mersenne-Twister',",
        "sample.kind = 'Rejection') for explicit reproducibility."
      ),
      reference    = "https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.3.html",
      closed       = TRUE
    )
  ),

  # ---- stringr ------------------------------------------------------------

  "stringr::str_c" = list(
    list(
      from_version = "1.4.99",
      to_version   = "1.6.9",
      risk         = "medium",
      description  = paste0(
        "In stringr 1.5.0, str_c() changed how it handles NULL",
        "inputs: NULLs are now silently ignored rather than treated",
        "as zero-length vectors. Code that passed NULL to str_c()",
        "expecting it to act as a length-0 vector (e.g. in",
        "conditional string-building patterns) will silently produce",
        "different output. Note: the separate NA-propagation",
        "behaviour (str_c('x', NA) returning NA) has been the",
        "default since stringr 1.0.0 -- use str_replace_na() on",
        "inputs if the old 'xNA' concatenation is needed."
      ),
      reference = "https://stringr.tidyverse.org/news/index.html"
    )
  ),

  "stringr::str_replace_all" = list(
    list(
      from_version = "1.5.99",
      to_version   = "1.6.9",
      risk         = "high",
      description  = paste0(
        "In stringr 1.6.0, str_replace_all() with a function as the",
        "replacement argument changed: the function now receives all",
        "matches from the entire input vector in a single call,",
        "rather than one call per match. Code using a replacement",
        "function that relies on state, side effects, or sequential",
        "per-match processing (e.g. a counter or accumulator) will",
        "silently produce wrong results. Stateless vectorised",
        "replacement functions are unaffected."
      ),
      reference = "https://stringr.tidyverse.org/news/index.html"
    )
  ),

  # ---- survival -----------------------------------------------------------

  "survival::coxph" = list(
    list(
      from_version = "3.1.99",
      to_version   = "3.8.9",
      risk         = "low",
      description  = paste0(
        "In survival 3.2-9, coxph() changed its default handling of",
        "0/1 predictors: they are no longer recentered (fit$mean is",
        "now 0 for binary predictors, rather than the column mean).",
        "Code that uses fit$mean for prediction centering, or calls",
        "survfit(fit) without specifying newdata for a model with",
        "binary/factor predictors, may silently produce different",
        "results. Use the nocenter argument to control this behavior",
        "explicitly."
      ),
      reference = "https://cran.r-project.org/web/packages/survival/news.html"
    )
  ),

  "survival::survfit" = list(
    list(
      from_version = "2.99.99",
      to_version   = "3.8.9",
      risk         = "medium",
      description  = paste0(
        "In survival 3.0, the survfit routines underwent a major",
        "revision to support multi-state coxph models. As part of",
        "this revision, survfit(cox_model) now returns an object of",
        "class 'survfitcox' rather than 'survfit.cox'. Code that",
        "checks the class of a survfit result (e.g. inherits(fit,",
        "'survfit.cox') or class(fit) == 'survfit.cox') will",
        "silently fail to match. Additionally, subscripting a",
        "survfit object now removes the na.action component."
      ),
      reference = "https://cran.r-project.org/web/packages/survival/news.html"
    )
  ),

  # ---- tibble -------------------------------------------------------------

  "tibble::tibble" = list(
    list(
      from_version = "2.1.99",
      to_version   = "3.9.9",
      risk         = "high",
      description  = paste0(
        "In tibble 3.0.0, strict vctrs-based recycling was fully",
        "enforced: only vectors of length 1 are recycled to match",
        "the tibble size. Code using tibble(x = 1:6, y = 1:2) or",
        "similar patterns where a non-length-1 vector was previously",
        "recycled silently will now error with 'Tibble columns must",
        "have consistent sizes, only values of size one are",
        "recycled'. This was warned in tibble 2.0.0 but became an",
        "error in 3.0.0. Analyses relying on implicit recycling of",
        "repeated block vectors will produce silent correctness",
        "errors or fail outright after upgrading."
      ),
      reference = "https://www.tidyverse.org/blog/2020/04/tibble-3-0-0/"
    )
  ),

  # ---- tidyr --------------------------------------------------------------

  "tidyr::nest" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.3.9",
      risk         = "high",
      description  = paste0(
        "In tidyr 1.0.0, nest() and unnest() were overhauled with",
        "new syntax: nest(x, y, z) became nest(data = c(x, y, z)),",
        "and the first argument changed from data to .data.",
        "Additionally, nest() now preserves grouping from",
        "dplyr::group_by(), which affects downstream group-aware",
        "calls like mutate() and filter(). Old positional-column",
        "usage of nest() generates a translation warning but may not",
        "always translate correctly, and code relying on nest()",
        "*not* preserving groups may now silently behave",
        "differently."
      ),
      reference = "https://rdrr.io/cran/tidyr/f/NEWS.md"
    )
  ),

  "tidyr::pivot_longer" = list(
    list(
      from_version = "1.2.99",
      to_version   = "1.3.9",
      risk         = "medium",
      description  = paste0(
        "In tidyr 1.3.0, the ... argument of pivot_longer() was",
        "moved to appear after the required arguments but before",
        "optional ones. Code relying on positional argument matching",
        "for optional parameters after names_to may silently pass",
        "values to the wrong argument. Additionally, values_ptypes =",
        "list() and names_ptypes = list() no longer mean NULL: an",
        "empty list() is now interpreted as a <list> prototype",
        "applied to all columns, changing type coercion behaviour",
        "for scripts that relied on the old interpretation."
      ),
      reference = "https://tidyr.tidyverse.org/news/index.html#tidyr-130"
    )
  ),

  "tidyr::pivot_wider" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.3.9",
      risk         = "medium",
      description  = paste0(
        "tidyr 1.0.0 introduced pivot_wider() as a replacement for",
        "spread(). Unlike spread(), which silently kept the last",
        "value for duplicate identifier rows, pivot_wider() with the",
        "default values_fn = NULL produces list-columns (with a",
        "warning) when identifiers are not unique, rather than",
        "silently picking one value. Code migrated from spread() to",
        "pivot_wider() without specifying values_fn may now get",
        "list-columns or warnings instead of the previously silent",
        "last-value-wins behaviour. tidyr 1.2.0 further improved the",
        "diagnostic message shown in this situation."
      ),
      reference = "https://rdrr.io/cran/tidyr/f/NEWS.md"
    )
  ),

  "tidyr::separate" = list(
    list(
      from_version = "1.2.99",
      to_version   = "1.3.9",
      risk         = "medium",
      description  = paste0(
        "In tidyr 1.3.0, separate() was superseded by the",
        "separate_wider_delim(), separate_wider_position(), and",
        "separate_wider_regex() family. Code using separate() will",
        "receive deprecation warnings. More critically, separate()",
        "is no longer maintained and silently produces different",
        "results for edge cases involving regex special characters",
        "or unequal split counts. Scripts should be migrated to the",
        "separate_wider_* equivalents which provide explicit,",
        "testable behaviour for problem handling."
      ),
      reference = "https://tidyr.tidyverse.org/news/index.html#tidyr-130"
    )
  ),

  "tidyr::unnest" = list(
    list(
      from_version = "0.8.99",
      to_version   = "1.3.9",
      risk         = "medium",
      description  = paste0(
        "In tidyr 1.0.0, unnest() was rewritten. The old interface",
        "(passing multiple columns positionally) changed; .drop and",
        ".id arguments were removed. Code using the old unnest() API",
        "may silently change structure."
      ),
      reference = "https://tidyr.tidyverse.org/news/index.html"
    )
  )

)

# ---- internal helpers ---------------------------------------------------

#' List all keys in the breaking-changes database
#' @noRd
.list_db_keys <- function() names(.BREAKING_CHANGES_DB)

#' Get breaking-change entries for a pkg::fn key
#' @noRd
.get_breaking_changes <- function(key) .BREAKING_CHANGES_DB[[key]]

